repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: Ruff Format
        entry: make format
        language: system
        types: [python]

      - id: ruff-lint
        name: Ruff Lint
        entry: make lint
        language: system
        types: [python]
